language: python
python:
  - "2.7"
install:
  - pip install flake8
  - pip install flake8-docstrings
  - pip install flake8-import-order
  - pip install flake8-todo
  - pip install .
jobs:
  inclue:
    - stage: metrics
      name: "style_guide"
      python: "2.7"
      script: flake8 --select=E,W,I,T --tee --output-file=pep8_violations.txt --statistics --count setup.py ImageCrypt && flake8 --select=D --tee --output-file=pep257_violations.txt --statistics --count setup.py ImageCrypt
    - name: "code_errors"
      python: "2.7"
      script: flake8 --select=F --tee --statistics --count setup.py ImageCrypt
    - name: "code_complexity"
      python: "2.7"
      script: flake8 --select=C901 --tee --count
  allow_failures:
    - name: "style_guide"