language: python
python:
  - "2.7"
install:
  - pip install flake8
  - pip install flake8-docstrings
  - pip install flake8-import-order
  - pip install flake8-todo
  - pip install .

jobs:
  include:
    - stage: metrics
      name: "Style Guide PEB8"
      python: "2.7"
      script: flake8 --select=E,W,I,T --tee --statistics --count setup.py ImageCrypt
    - stage: metrics
      name: "Style Guide PEB257"
      python: "2.7"
      script: flake8 --select=D --tee --statistics --count setup.py ImageCrypt
    - stage: metrics
      name: "Code Errors"
      python: "2.7"
      script: flake8 --select=F --tee --statistics --count setup.py ImageCrypt
    - stage: metrics
      name: "Code Complexity"
      python: "2.7"
      script: flake8 --select=C901 --tee --count
  allow_failures:
    - name: "Style Guide PEB257"